import type { DisplaySearchResult } from "./types";
import { LEVEL_ACCENT, LEVEL_LABEL, LEVEL_HASH } from "./types";

export const SEED_BUSINESSES: Omit<
  DisplaySearchResult,
  "accentColor" | "levelLabel" | "hash" | "id" | "relevance_score" | "block_count"
>[] = [
  {
    name: "Meridian Logistics Co.",
    slug: "meridian-logistics-co",
    verification_level: "full",
    hasVideo: true,
    iso: "DE",
    authority: "Handelsregister",
    requirement: "HRB extract + UBO disclosure",
    registryId: "REG·DE·HRB-88412",
    badges: [],
    badgePills: [{ text: "Registry" }, { text: "C2PA Media" }, { text: "Bitcoin TS" }],
    country: "DE",
    registry_id: "HRB-88412",
    registry_data: {
      registry: "Handelsregister",
      registration_number: "HRB-88412",
      legal_name: "Meridian Logistics Co. GmbH",
      status: "active",
      verified_at: "2026-06-01T00:00:00Z",
    },
    entity_type: "business" as const,
    agent_endpoint: null,
    agent_endpoint_verified: false,
    ai_categories: { industry: "logistics", confidence: 0.95 },
    description:
      "Autonomous freight coordination and cross-border customs attestation for agent-managed supply chains.",
  },
  {
    name: "Halcyon Health Systems",
    slug: "halcyon-health-systems",
    verification_level: "full",
    hasVideo: true,
    iso: "US",
    authority: "Delaware SoS · IRS EIN",
    requirement: "Good-standing cert + EIN match",
    registryId: "REG·US·EIN-47-2210",
    badges: [],
    badgePills: [{ text: "Registry" }, { text: "C2PA Media" }, { text: "Bitcoin TS" }],
    country: "US",
    registry_id: "EIN-47-2210",
    registry_data: {
      registry: "Delaware SoS · IRS",
      registration_number: "EIN-47-2210",
      legal_name: "Halcyon Health Systems LLC",
      status: "active",
      verified_at: "2026-06-01T00:00:00Z",
    },
    entity_type: "business" as const,
    agent_endpoint: null,
    agent_endpoint_verified: false,
    ai_categories: { industry: "healthcare", confidence: 0.92 },
    description:
      "Clinical data exchange with patient-consent verification and signed provenance for diagnostic media.",
  },
  {
    name: "Atlas Provenance Studio",
    slug: "atlas-provenance-studio",
    verification_level: "full",
    hasVideo: true,
    iso: "NL",
    authority: "Kamer van Koophandel",
    requirement: "KvK uittreksel + UBO register",
    registryId: "REG·NL·KVK-7740",
    badges: [],
    badgePills: [{ text: "Registry" }, { text: "C2PA Media" }, { text: "Bitcoin TS" }],
    country: "NL",
    registry_id: "KVK-7740",
    registry_data: {
      registry: "Kamer van Koophandel",
      registration_number: "KVK-7740",
      legal_name: "Atlas Provenance Studio B.V.",
      status: "active",
      verified_at: "2026-06-01T00:00:00Z",
    },
    entity_type: "business" as const,
    agent_endpoint: null,
    agent_endpoint_verified: false,
    ai_categories: { industry: "media", confidence: 0.91 },
    description:
      "C2PA-signed media production and content authenticity pipelines for brand-safe agent distribution.",
  },
  {
    name: "Northwind Capital Partners",
    slug: "northwind-capital-partners",
    verification_level: "partial",
    hasVideo: false,
    iso: "UK",
    authority: "Companies House",
    requirement: "CRN filing + PSC register",
    registryId: "REG·UK·CRN-09912",
    badges: [],
    badgePills: [{ text: "Registry" }, { text: "Bitcoin TS" }],
    country: "GB",
    registry_id: "CRN-09912",
    registry_data: {
      registry: "Companies House",
      registration_number: "CRN-09912",
      legal_name: "Northwind Capital Partners Ltd",
      status: "active",
      verified_at: "2026-06-01T00:00:00Z",
    },
    entity_type: "business" as const,
    agent_endpoint: null,
    agent_endpoint_verified: false,
    ai_categories: { industry: "finance", confidence: 0.88 },
    description:
      "Programmatic credit underwriting and timestamped disclosure records for SMB lending agents.",
  },
  {
    name: "Coriolis Maritime",
    slug: "coriolis-maritime",
    verification_level: "partial",
    hasVideo: false,
    iso: "SG",
    authority: "ACRA",
    requirement: "UEN bizfile + officer list",
    registryId: "REG·SG·UEN-2018",
    badges: [],
    badgePills: [{ text: "Registry" }, { text: "Bitcoin TS" }],
    country: "SG",
    registry_id: "UEN-2018",
    registry_data: {
      registry: "ACRA",
      registration_number: "UEN-2018",
      legal_name: "Coriolis Maritime Pte Ltd",
      status: "active",
      verified_at: "2026-06-01T00:00:00Z",
    },
    entity_type: "business" as const,
    agent_endpoint: null,
    agent_endpoint_verified: false,
    ai_categories: { industry: "maritime", confidence: 0.93 },
    description:
      "Vessel tracking and cargo manifest attestation with verifiable bills of lading.",
  },
  {
    name: "Vega Energy Markets",
    slug: "vega-energy-markets",
    verification_level: "registry",
    hasVideo: false,
    iso: "FR",
    authority: "Registre du Commerce",
    requirement: "SIREN extract (Kbis)",
    registryId: "REG·FR·SIREN-552",
    badges: [],
    badgePills: [{ text: "Registry" }],
    country: "FR",
    registry_id: "SIREN-552",
    registry_data: {
      registry: "Registre du Commerce",
      registration_number: "SIREN-552",
      legal_name: "Vega Energy Markets SAS",
      status: "active",
      verified_at: "2026-06-01T00:00:00Z",
    },
    entity_type: "business" as const,
    agent_endpoint: null,
    agent_endpoint_verified: false,
    ai_categories: { industry: "energy", confidence: 0.87 },
    description:
      "Real-time grid balancing and renewable certificate trading. Registry standing confirmed.",
  },
  {
    name: "Foundry Microworks",
    slug: "foundry-microworks",
    verification_level: "registry",
    hasVideo: false,
    iso: "JP",
    authority: "Corporate Number (hōjin)",
    requirement: "Tōki extract + seal cert",
    registryId: "REG·JP·CN-1300",
    badges: [],
    badgePills: [{ text: "Registry" }],
    country: "JP",
    registry_id: "CN-1300",
    registry_data: {
      registry: "Corporate Number Database",
      registration_number: "CN-1300",
      legal_name: "Foundry Microworks K.K.",
      status: "active",
      verified_at: "2026-06-01T00:00:00Z",
    },
    entity_type: "business" as const,
    agent_endpoint: null,
    agent_endpoint_verified: false,
    ai_categories: { industry: "manufacturing", confidence: 0.89 },
    description:
      "Precision component manufacturing with ISO-attested process documentation.",
  },
];

export function getDisplayResults(
  data: typeof SEED_BUSINESSES = SEED_BUSINESSES
): DisplaySearchResult[] {
  return data.map((b, i) => ({
    ...b,
    id: `seed-${i}`,
    relevance_score: 0.9,
    block_count: b.hasVideo ? 3 : 1,
    accentColor: LEVEL_ACCENT[b.verification_level],
    levelLabel: LEVEL_LABEL[b.verification_level],
    hash: LEVEL_HASH[b.verification_level],
  }));
}
